//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import CardSkillFilterForm from "@/components/card-skills/CardSkillFilterForm";
import CardSkillTable from "@/components/card-skills/CardSkillTable";

export const metadata = {
  title: "Card Skills",
};

const CardSkills: React.FC = () => {
  return (
    <div className="flex flex-col flex-1 w-full px-4 mx-auto text-sm lg:px-0 main-height-less-footer">
      <div className="flex flex-col flex-1 w-full gap-4 p-4 border rounded-sm border-border">
        <h1 className="text-2xl font-bold">Card Skills</h1>
        <div className="flex">
          <CardSkillFilterForm />
        </div>
        <div className="flex flex-col flex-1 ">
          <CardSkillTable />
        </div>
      </div>
    </div>
  );
};

export default CardSkills;
