//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import LockedDeckCardFilterForm from "@/components/locked-deck-cards/LockedDeckCardFilterForm";
import LockedDeckCardTable from "@/components/locked-deck-cards/LockedDeckCardTable";

export const metadata = {
  title: "Locked Deck Cards",
};

const LockedDeckCards: React.FC = () => {
  return (
    <div className="flex flex-col flex-1 w-full px-4 mx-auto text-sm lg:px-0 main-height-less-footer">
      <div className="flex flex-col flex-1 w-full gap-4 p-4 border rounded-sm border-border">
        <h1 className="text-2xl font-bold">Locked Deck Cards</h1>
        <div className="flex">
          <LockedDeckCardFilterForm />
        </div>
        <div className="flex flex-col flex-1 ">
          <LockedDeckCardTable />
        </div>
      </div>
    </div>
  );
};

export default LockedDeckCards;
