//Generated by GetAllHeaderLinks - header-links
export const links = [
  { id: 0, name: "Home", href: "/" },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "cards", name: "Cards", href: "/cards" },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "decks", name: "Decks", href: "/decks" },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "hero-skills", name: "Hero Skills", href: "/hero-skills" },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "card-keywords", name: "Card Keywords", href: "/card-keywords" },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "card-unities", name: "Card Unities", href: "/card-unities" },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "locked-decks", name: "Locked Decks", href: "/locked-decks" },
];
