//Generated by WriteToModelconstants_ts - ModelConstants.ts
import { CardUnityCardFormikFilter } from "@/interfaces/CardUnityCardInterfaces";

export const MODEL_NAME = "CardUnityCard";
export const TABLE_NAME = "cardunitycards";
export const PLURALIZED_MODEL_NAME = "CardUnityCards";
export const VERBOSE_MODEL_NAME = "Card Unity Card";
export const PLURALIZED_VERBOSE_MODEL_NAME = "Card Unity Cards";
export const DEFAULT_SORT_BY = "id";
export const DEFAULT_FILTERS: Partial<CardUnityCardFormikFilter> = {
  //Generated by GetAllModelFilterDefaultBySeqModel
  q: "",
  card: "", //Generated by GetModelFilterDefault
};
export const FIRST_FIELD_IN_FORM = "CardId"; //Generated by GetFirstFieldInForm
export const LAST_FIELD_IN_FORM = "description"; //Generated by GetLastFieldInForm
export const DEFAULT_FORM_VALUE = {
  //Generated by GetAllFormDefaultValueBySeqModel
  id: "", //Generated by GetFormDefaultValue
  description: "", //Generated by GetFormDefaultValue
  CardUnityId: "", //Generated by GetFormDefaultValue
  CardId: "", //Generated by GetFormDefaultValue,
  touched: false,
};
export const PRIMARY_KEY = "id";
export const UNIQUE_FIELDS = [
  //Generated by GetAllUniqueFieldsBySeqModel
];
export const REQUIRED_FIELDS = {
  //Generated by GetAllRequiredFieldsBySeqModel
  description: "Description", //Generated by GetRequiredField - Get Required Field
  CardUnityId: "Card Unity", //Generated by GetRequiredField - Get Required Field
  CardId: "Card", //Generated by GetRequiredField - Get Required Field
};

//Generated by GetControlOptionsBySeqModel
export const CONTROL_OPTIONS = {};

//Generated by GetCOLUMNSObject
export const COLUMNS = {
  id: { type: "number", db_name: "id" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  description: { type: "string", db_name: "description" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  CardUnityId: { type: "number", db_name: "CardUnityId" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  CardId: { type: "number", db_name: "CardId" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
};
