//Generated by WriteToModelconstants_ts - ModelConstants.ts
import { CardCardKeywordFormikFilter } from "@/interfaces/CardCardKeywordInterfaces";

export const MODEL_NAME = "CardCardKeyword";
export const TABLE_NAME = "marvelduel_card_card_keywords";
export const PLURALIZED_MODEL_NAME = "CardCardKeywords";
export const VERBOSE_MODEL_NAME = "Card Card Keyword";
export const PLURALIZED_VERBOSE_MODEL_NAME = "Card Card Keywords";
export const DEFAULT_SORT_BY = "id";
export const DEFAULT_FILTERS: Partial<CardCardKeywordFormikFilter> = {
  //Generated by GetAllModelFilterDefaultBySeqModel
};
export const FIRST_FIELD_IN_FORM = "cardId"; //Generated by GetFirstFieldInForm
export const LAST_FIELD_IN_FORM = "cardKeywordId"; //Generated by GetLastFieldInForm
export const DEFAULT_FORM_VALUE = {
  //Generated by GetAllFormDefaultValueBySeqModel
  id: "", //Generated by GetFormDefaultValue
  cardId: "", //Generated by GetFormDefaultValue
  cardKeywordId: "", //Generated by GetFormDefaultValue,
  touched: false,
};
export const PRIMARY_KEY = "id";
export const UNIQUE_FIELDS = [
  //Generated by GetAllUniqueFieldsBySeqModel
];
export const REQUIRED_FIELDS = {
  //Generated by GetAllRequiredFieldsBySeqModel
  cardId: "Card", //Generated by GetRequiredField - Get Required Field
  cardKeywordId: "Card Keyword", //Generated by GetRequiredField - Get Required Field
};

//Generated by GetCOLUMNSObject
export const COLUMNS = {
  id: { type: "number", db_name: "id" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  cardId: { type: "number", db_name: "card_id" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  cardKeywordId: { type: "number", db_name: "cardkeyword_id" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
};
