//Generated by WriteToModelconstants_ts - ModelConstants.ts
import { CardUnityFormikFilter } from "@/interfaces/CardUnityInterfaces";
import { convertDateToYYYYMMDD } from "@/utils/utilities";

export const MODEL_NAME = "CardUnity";
export const TABLE_NAME = "cardunities";
export const PLURALIZED_MODEL_NAME = "CardUnities";
export const VERBOSE_MODEL_NAME = "Card Unity";
export const PLURALIZED_VERBOSE_MODEL_NAME = "Card Unities";
export const DEFAULT_SORT_BY = "-id";
export const DEFAULT_FILTERS: Partial<CardUnityFormikFilter> = {
  //Generated by GetAllModelFilterDefaultBySeqModel
  q: "",
  card: "", //Generated by GetModelFilterDefault
};
export const FIRST_FIELD_IN_FORM = "cardCompositions"; //Generated by GetFirstFieldInForm
export const LAST_FIELD_IN_FORM = "cardCompositions"; //Generated by GetLastFieldInForm
export const DEFAULT_FORM_VALUE = {
  //Generated by GetAllFormDefaultValueBySeqModel
  id: "", //Generated by GetFormDefaultValue
  cardCompositions: "", //Generated by GetFormDefaultValue,
  touched: false,
};
export const PRIMARY_KEY = "id";
export const UNIQUE_FIELDS = [
  //Generated by GetAllUniqueFieldsBySeqModel
  { cardCompositions: "Card Compositions" },
];
export const REQUIRED_FIELDS = {
  //Generated by GetAllRequiredFieldsBySeqModel
  cardCompositions: "Card Compositions", //Generated by GetRequiredField - Get Required Field
};

//Generated by GetControlOptionsBySeqModel
export const CONTROL_OPTIONS = {};

//Generated by GetCOLUMNSObject
export const COLUMNS = {
  id: { type: "number", db_name: "id" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  cardCompositions: { type: "string", db_name: "cardCompositions" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
};
