//Generated by WriteToModelconstants_ts - ModelConstants.ts
import { HeroFormikFilter } from "@/interfaces/HeroInterfaces";

export const MODEL_NAME = "Hero";
export const TABLE_NAME = "marvelduel_hero";
export const PLURALIZED_MODEL_NAME = "Heroes";
export const VERBOSE_MODEL_NAME = "Hero";
export const PLURALIZED_VERBOSE_MODEL_NAME = "Heroes";
export const DEFAULT_SORT_BY = "belongsto_id";
export const DEFAULT_FILTERS: Partial<HeroFormikFilter> = {
  //Generated by GetAllModelFilterDefaultBySeqModel
};
export const FIRST_FIELD_IN_FORM = "heroName"; //Generated by GetFirstFieldInForm
export const LAST_FIELD_IN_FORM = "heroName"; //Generated by GetLastFieldInForm
export const DEFAULT_FORM_VALUE = {
  //Generated by GetAllFormDefaultValueBySeqModel
  belongsto_id: "", //Generated by GetFormDefaultValue
  heroName: "", //Generated by GetFormDefaultValue,
  touched: false,
};
export const PRIMARY_KEY = "belongsto_id";
export const UNIQUE_FIELDS = [
  //Generated by GetAllUniqueFieldsBySeqModel
  { heroName: "Hero Name" },
];
export const REQUIRED_FIELDS = {
  //Generated by GetAllRequiredFieldsBySeqModel
};

//Generated by GetControlOptionsBySeqModel
export const CONTROL_OPTIONS = {};

//Generated by GetCOLUMNSObject
export const COLUMNS = {
  belongsto_id: { type: "number", db_name: "belongsto_id" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  heroName: { type: "string", db_name: "hero_name" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
};
