//Generated by WriteToModelconstants_ts
import { HeroFormikFilter } from "@/interfaces/HeroInterfaces";

export const MODEL_NAME = "Hero";
export const TABLE_NAME = "marvelduel_hero";
export const PLURALIZED_MODEL_NAME = "Heroes";
export const DEFAULT_SORT_BY = "belongsto_id";
export const DEFAULT_FILTERS: Partial<HeroFormikFilter> = {
  //Generated by GetAllModelFilterDefaultBySeqModel
};
export const FIRST_FIELD_IN_FORM = "heroName";
export const LAST_FIELD_IN_FORM = "heroName";
export const DEFAULT_FORM_VALUE = {
  //Generated by GetAllFormDefaultValueBySeqModel
  belongsto_id: "",
  heroName: "",
  touched: false,
};
export const PRIMARY_KEY = "belongsto_id";
export const UNIQUE_FIELDS = [
  //Generated by GetAllUniqueFieldsBySeqModel
];
export const REQUIRED_FIELDS = {
  //Generated by GetAllRequiredFieldsBySeqModel
};
