//Generated by WriteToModelconstants_ts
import { HeroSkillFormikFilter } from "@/interfaces/HeroSkillInterfaces";

export const MODEL_NAME = "HeroSkill";
export const TABLE_NAME = "marvelduel_heroskill";
export const PLURALIZED_MODEL_NAME = "HeroSkills";
export const VERBOSE_MODEL_NAME = "Hero Skill";
export const PLURALIZED_VERBOSE_MODEL_NAME = "Hero Skills";
export const DEFAULT_SORT_BY = "name";
export const DEFAULT_FILTERS: Partial<HeroSkillFormikFilter> = {
  //Generated by GetAllModelFilterDefaultBySeqModel
  q: "",
  type: "",
  hero: [],
};
export const FIRST_FIELD_IN_FORM = "name";
export const LAST_FIELD_IN_FORM = "heroId";
export const DEFAULT_FORM_VALUE = {
  //Generated by GetAllFormDefaultValueBySeqModel
  id: "",
  name: "",
  type: "Active" as const,
  cost: "",
  description: "",
  heroId: "",
  touched: false,
};
export const PRIMARY_KEY = "id";
export const UNIQUE_FIELDS = [
  //Generated by GetAllUniqueFieldsBySeqModel
  { name: "Name" },
];
export const REQUIRED_FIELDS = {
  //Generated by GetAllRequiredFieldsBySeqModel
  name: "Name",
  type: "Type",
  description: "Description",
  heroId: "Hero",
};

//Generated by GetControlOptionsBySeqModel
export const CONTROL_OPTIONS = {
  type: [
    { id: "Active", name: "Active" },
    { id: "Passive", name: "Passive" },
  ],
};

//Generated by GetCOLUMNSObject
export const COLUMNS = {
  id: { type: "number" },
  name: { type: "string" },
  type: { type: "string" },
  cost: { type: "number" },
  description: { type: "string" },
  heroId: { type: "number" },
};
