//Generated by WriteToModelconstants_ts - ModelConstants.ts
import { HeroSkillFormikFilter } from "@/interfaces/HeroSkillInterfaces";

export const MODEL_NAME = "HeroSkill";
export const TABLE_NAME = "marvelduel_heroskill";
export const PLURALIZED_MODEL_NAME = "HeroSkills";
export const VERBOSE_MODEL_NAME = "Hero Skill";
export const PLURALIZED_VERBOSE_MODEL_NAME = "Hero Skills";
export const DEFAULT_SORT_BY = "name";
export const DEFAULT_FILTERS: Partial<HeroSkillFormikFilter> = {
  //Generated by GetAllModelFilterDefaultBySeqModel
  q: "",
  type: "", //Generated by GetModelFilterDefault
  hero: [], //Generated by GetModelFilterDefault
};
export const FIRST_FIELD_IN_FORM = "name"; //Generated by GetFirstFieldInForm
export const LAST_FIELD_IN_FORM = "heroId"; //Generated by GetLastFieldInForm
export const DEFAULT_FORM_VALUE = {
  //Generated by GetAllFormDefaultValueBySeqModel
  id: "", //Generated by GetFormDefaultValue
  name: "", //Generated by GetFormDefaultValue
  type: "Active" as const, //Generated by GetFormDefaultValue
  cost: "", //Generated by GetFormDefaultValue
  description: "", //Generated by GetFormDefaultValue
  heroId: "", //Generated by GetFormDefaultValue,
  touched: false,
};
export const PRIMARY_KEY = "id";
export const UNIQUE_FIELDS = [
  //Generated by GetAllUniqueFieldsBySeqModel
  { name: "Name" },
];
export const REQUIRED_FIELDS = {
  //Generated by GetAllRequiredFieldsBySeqModel
  name: "Name", //Generated by GetRequiredField - Get Required Field
  type: "Type", //Generated by GetRequiredField - Get Required Field
  description: "Description", //Generated by GetRequiredField - Get Required Field
  heroId: "Hero", //Generated by GetRequiredField - Get Required Field
};

//Generated by GetControlOptionsBySeqModel
export const CONTROL_OPTIONS = {
  type: [
    { id: "Active", name: "Active" },
    { id: "Passive", name: "Passive" },
  ], //Generated by GetFieldOptions
};

//Generated by GetCOLUMNSObject
export const COLUMNS = {
  id: { type: "number", db_name: "id" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  name: { type: "string", db_name: "name" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  type: { type: "string", db_name: "type" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  cost: { type: "number", db_name: "cost" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  description: { type: "string", db_name: "description" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  heroId: { type: "number", db_name: "hero_id" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
};
