//Generated by WriteToModelsPage - Model Page
import React from "react";
import CardUnityFilterForm from "@/components/card-unities/CardUnityFilterForm";
import CardUnityTable from "@/components/card-unities/CardUnityTable";

export const metadata = {
  title: "Card Unities",
};

const CardUnities: React.FC = () => {
  return (
    <div className="flex flex-col flex-1 w-full max-w-screen-lg px-4 mx-auto text-sm lg:px-0">
      <div className="flex flex-col w-full gap-4 p-4 border rounded-sm border-border">
        <h1 className="text-2xl font-bold">Card Unities</h1>
        <div className="flex">
          <CardUnityFilterForm />
        </div>
        <div className="flex flex-col flex-1 ">
          <CardUnityTable />
        </div>
      </div>
    </div>
  );
};

export default CardUnities;
