//Generated by WriteToMultiRoute_ts - multi route.ts
import { createHeroSkill, updateHeroSkill } from "@/app/api/hero-skills/route";
import sequelize from "@/config/db";
import { HeroSkillUpdatePayload } from "@/interfaces/HeroSkillInterfaces";
import { HeroSkillSchema } from "@/schema/HeroSkillSchema";
import {
  PRIMARY_KEY,
  UNIQUE_FIELDS,
} from "@/utils/constants/HeroSkillConstants";
import handleSequelizeError from "@/utils/errorHandling";
import { checkDuplicateCombinations, returnJSONResponse } from "@/utils/utils";
import { NextResponse } from "next/server";

//Generated by GetMultiCreateModelPOSTRoute - GetMultiCreateModelPOSTRoute
export const POST = async (req: Request) => {
  const body = (await req.json()) as HeroSkillUpdatePayload;
  const { HeroSkills } = body;

  //Generated by GenerateUniquenessValidation
  //Validate record uniqueness

  UNIQUE_FIELDS.forEach((item) => {
    const uniquenessError = checkDuplicateCombinations(item, HeroSkills);

    if (uniquenessError) {
      return returnJSONResponse({
        status: "error",
        error: uniquenessError,
        errorCode: 422,
      });
    }
  });

  const t = await sequelize.transaction();
  let recordsCreated = 0;

  for (const item of HeroSkills) {
    try {
      await HeroSkillSchema.validate(item);
    } catch (error) {
      return handleSequelizeError(error);
    }
  }

  try {
    for (const item of HeroSkills) {
      if (item[PRIMARY_KEY] === "") {
        await createHeroSkill(item, t);
        recordsCreated++;
      } else {
        await updateHeroSkill(item, PRIMARY_KEY, t);
      }
    }

    await t.commit();

    return NextResponse.json({
      recordsCreated,
    });
  } catch (err) {
    await t.rollback();
    return handleSequelizeError(err);
  }
};
