//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import CardFilterForm from "@/components/cards/CardFilterForm";
import CardTable from "@/components/cards/CardTable";

export const metadata = {
  title: "Cards",
};

const Cards: React.FC = () => {
  return (
    <div className="flex flex-col flex-1 w-full px-4 mx-auto text-sm lg:px-0 main-height-less-footer">
      <div className="flex flex-col flex-1 w-full mx-auto gap-4 p-4 border rounded-sm border-border">
        <h1 className="text-2xl font-bold">Cards</h1>
        <div className="flex">
          <CardFilterForm />
        </div>
        <div className="flex flex-col flex-1 ">
          <CardTable />
        </div>
      </div>
    </div>
  );
};

export default Cards;
