//Generated by GeneratePageFile
import { FormikCombobox } from "@/components/formik/FormikCombobox";
import { FormikFacetedControl } from "@/components/formik/FormikFacetedControl";
import { FormikInput } from "@/components/formik/FormikInput";
import { FormikSelect } from "@/components/formik/FormikSelect";
import { FormikSwitch } from "@/components/formik/FormikSwitch";
import { BasicModel } from "@/interfaces/GeneralInterfaces";
import { ClassValue } from "clsx";
import React from "react";

interface ControlProps {
  name: string;
  label?: string;
  submitOnChange?: boolean;
  placeholder?: string;
  containerClassNames?: ClassValue[];
}

interface TextProps extends ControlProps {
  type: "Text";
}

interface SwitchProps extends ControlProps {
  type: "Switch";
}

interface ComboBoxProps extends ControlProps {
  type: "ComboBox";
  options: BasicModel[];
  showLabel: boolean;
}

interface SelectProps extends ControlProps {
  type: "Select";
  options: BasicModel[];
  showLabel: boolean;
  allowBlank?: boolean;
}

interface FacetedControlProps extends ControlProps {
  type: "FacetedControl";
  options: BasicModel[];
}

type FormikControlProps =
  | FacetedControlProps
  | TextProps
  | SwitchProps
  | ComboBoxProps
  | SelectProps;

const FormikControl: React.FC<FormikControlProps> = (props) => {
  const {
    type,
    name,
    label = "",
    submitOnChange,
    containerClassNames,
    placeholder,
  } = props;
  switch (type) {
    case "Switch":
      return (
        <FormikSwitch
          name={name}
          label={label}
          submitOnChange={submitOnChange}
          containerClassNames={containerClassNames}
        />
      );
    case "FacetedControl":
      return (
        <FormikFacetedControl
          name={name}
          options={props.options}
          label={label}
          containerClassNames={containerClassNames}
        />
      );
    case "ComboBox":
      return (
        <FormikCombobox
          name={name}
          items={props.options}
          label={label}
          containerClassNames={containerClassNames}
          showLabel={false}
        />
      );
    case "Select":
      return (
        <FormikSelect
          name={name}
          options={props.options}
          label={label}
          containerClassNames={containerClassNames}
          showLabel={false}
          allowBlank={props.allowBlank || false}
        />
      );
    default:
      return (
        <FormikInput
          name={name}
          label={label}
          submitOnChange={submitOnChange}
          placeholder={placeholder}
          containerClassNames={containerClassNames}
        />
      );
  }
};

export default FormikControl;
