//Generated by GeneratePageFile
import { FormikInput } from "@/components/formik/FormikInput";
import { FormikSwitch } from "@/components/formik/FormikSwitch";
import { ClassValue } from "clsx";
import React from "react";

interface FormikControlProps {
  name: string;
  label?: string;
  submitOnChange?: boolean;
  placeholder?: string;
  type: string;
  containerClassNames?: ClassValue[];
}

const FormikControl: React.FC<FormikControlProps> = ({
  name,
  label,
  submitOnChange = false,
  placeholder,
  containerClassNames,
  type,
}) => {
  if (type === "Switch") {
    return (
      <FormikSwitch
        name={name}
        label={label}
        submitOnChange={submitOnChange}
        containerClassNames={containerClassNames}
      />
    );
  }

  return (
    <FormikInput
      name={name}
      label={label}
      submitOnChange={submitOnChange}
      placeholder={placeholder}
      containerClassNames={containerClassNames}
    />
  );
};

export default FormikControl;
