//Generated by WriteToModelsRouteApi - models route next 13
import { CardUnity } from "@/models/CardUnityModel";
import { FindOptions, Transaction } from "sequelize";
import { cloneDeep } from "lodash";
import {
  checkDuplicateCombinations,
  formatSortAsSequelize,
  getSort,
  parseParams,
  returnJSONResponse,
} from "@/utils/utils";
import { genericGetAll } from "@/utils/generic";
import sequelize from "@/config/db";
import handleSequelizeError from "@/utils/errorHandling";
import { Op } from "sequelize";
import {
  CardUnityDeletePayload,
  CardUnityFormikShape,
  CardUnitySearchParams,
  CardUnityUpdatePayload,
} from "@/interfaces/CardUnityInterfaces";
import { NextResponse } from "next/server";
import { DEFAULT_LIMIT } from "@/utils/constants";
import {
  DEFAULT_SORT_BY,
  PRIMARY_KEY,
  REQUIRED_FIELDS,
  UNIQUE_FIELDS,
} from "@/utils/constants/CardUnityConstants";
import { CardUnitySchema } from "@/schema/CardUnitySchema";
import { appendAndFilters, getCursor } from "@/utils/api/utils";

const ModelObject = CardUnity;

//Generated by GeneratefindOptions
const findOptions: FindOptions<typeof CardUnity> = {
  //Generated by GenerateIncludeOption
  include: [],
  //Generated by GenerateAttributesOption
  attributes: [
    //Generated by GetAllModelAttributesBySeqModel
    "id",
    "cardCompositions",
    "createdAt",
    "updatedAt",
  ],
};

//Reusable functions
export const createCardUnity = async (
  cardUnity: Omit<CardUnityFormikShape, "touched">,
  t: Transaction
) => {
  return await CardUnity.create(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
      cardCompositions: cardUnity.cardCompositions!,
    },
    { transaction: t }
  );
};

export const updateCardUnity = async (
  cardUnity: Omit<CardUnityFormikShape, "touched" | "index">,
  primaryKey: keyof Omit<CardUnityFormikShape, "touched" | "index">,
  t: Transaction,
  primaryKeyValue?: string | number
) => {
  await CardUnity.update(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
      cardCompositions: cardUnity.cardCompositions!,
    },
    {
      where: { [primaryKey]: primaryKeyValue || cardUnity[primaryKey] },
      transaction: t,
      individualHooks: true,
    }
  );
};

export const deleteCardUnities = async (
  primaryKey: keyof Omit<CardUnityFormikShape, "touched">,
  deletedIds: string[] | number[],
  t: Transaction
) => {
  await CardUnity.destroy({
    where: { [primaryKey]: { [Op.in]: deletedIds } },
    transaction: t,
  });
};

//Generated by Generate_getModelsSimpleFilterNext13
export const GET = async (req: Request) => {
  //Generated by Generate_findOptionsCopy
  const findOptionsCopy: FindOptions<typeof CardUnity> = cloneDeep(findOptions);
  const cardUnityAttributes = Object.keys(CardUnity.getAttributes()).map(
    (attribute) => attribute
  );

  const searchParams = new URL(req.url).searchParams;

  const query = parseParams(searchParams) as Partial<CardUnitySearchParams>;
  const primaryKey = PRIMARY_KEY;

  const simpleOnly = query["simpleOnly"];
  const cursor = query["cursor"];
  const fetchCount = query["fetchCount"] === "true";

  let limit = query["limit"];
  const sort = query["sort"]
    ? cardUnityAttributes.includes(query["sort"]) ||
      cardUnityAttributes.includes(query["sort"].substring(1))
      ? query["sort"]
      : DEFAULT_SORT_BY
    : DEFAULT_SORT_BY;

  //Remove the - from the sort parameter
  const sortField = sort.includes("-") ? sort.substring(1) : sort;

  if (!simpleOnly) {
    const where: Record<string | symbol, unknown> = { [Op.and]: [] };
    const andFilters = [];

    const q = query["q"];

    if (q) {
      andFilters.push({
        [Op.or]: [
          //Generated by GetAllQFilterFieldBySeqModel
          //Generated by GenerateAQFilterField - GenerateAQFilterField
        ],
      });
    }

    //Generated by GetAllBackendFiltersBySeqModel

    //get all the count here first
    let recordCount = 0;
    if (fetchCount) {
      recordCount = await CardUnity.count({
        where: { [Op.and]: andFilters },
      });
    }

    if (cursor) {
      appendAndFilters(andFilters, sort, sortField, primaryKey, cursor);
    }

    where[Op.and] = andFilters;
    findOptionsCopy.where = where;
    limit = limit || DEFAULT_LIMIT;
    findOptionsCopy.limit = parseInt(limit);

    //@ts-ignore
    findOptionsCopy.order = formatSortAsSequelize(
      getSort(sort, DEFAULT_SORT_BY, primaryKey)
    );

    try {
      const data = await CardUnity.findAll(findOptionsCopy);

      const cursor = getCursor(data, sortField, primaryKey);

      return NextResponse.json({
        rows: data,
        cursor,
        ...(fetchCount && { count: recordCount }),
      });
    } catch (err) {
      return handleSequelizeError(err);
    }
  } else {
    return genericGetAll(ModelObject, findOptionsCopy);
  }
};

export const POST = async (req: Request) => {
  const body = (await req.json()) as CardUnityUpdatePayload;
  const { CardUnities } = body;

  //Generated by GenerateUniquenessValidation
  //Validate record uniqueness

  UNIQUE_FIELDS.forEach((item) => {
    const uniquenessError = checkDuplicateCombinations(item, CardUnities);

    if (uniquenessError) {
      return returnJSONResponse({
        status: "error",
        error: uniquenessError,
        errorCode: 422,
      });
    }
  });

  const t = await sequelize.transaction();
  let recordsCreated = 0;

  for (const item of CardUnities) {
    try {
      await CardUnitySchema.validate(item);
    } catch (error) {
      return handleSequelizeError(error);
    }
  }

  try {
    for (const item of CardUnities) {
      if (item[PRIMARY_KEY] === "") {
        await createCardUnity(item, t);
        recordsCreated++;
      } else {
        await updateCardUnity(item, PRIMARY_KEY, t);
      }
    }

    await t.commit();

    return NextResponse.json({
      recordsCreated,
    });
  } catch (err) {
    await t.rollback();
    return handleSequelizeError(err);
  }
};

export const DELETE = async (req: Request) => {
  const body = (await req.json()) as CardUnityDeletePayload;
  const { deletedCardUnities } = body;

  if (deletedCardUnities.length > 0) {
    const t = await sequelize.transaction();
    try {
      await deleteCardUnities(PRIMARY_KEY, deletedCardUnities, t);
      t.commit();
      return NextResponse.json("success");
    } catch (error) {
      t.rollback();
      return handleSequelizeError(error);
    }
  }
};
