//Generated by WriteToModelfilterform_tsx
"use client";
import { useCardStore } from "@/hooks/cards/useCardStore";
import {
  CardFormikFilter,
  CardSearchParams,
} from "@/interfaces/CardInterfaces";
import { DEFAULT_LIMIT } from "@/utils/constants";
import { getFilterValueFromURL, getParamsObject } from "@/utils/utilities";
import { encodeParams } from "@/utils/utils";
import { Form, Formik, FormikHelpers, FormikProps } from "formik";
import React, { MouseEventHandler } from "react";
import {
  DEFAULT_FILTERS,
  CONTROL_OPTIONS,
} from "@/utils/constants/CardConstants";
import LimitSelector from "@/components/form/LimitSelector";
import { useURL } from "@/hooks/useURL";
import FormikControl from "@/components/form/FormikControl";
import { Button } from "@/components/ui/Button";
import { isEqual } from "lodash";
//Generated by ImportAllUseModelListHookBySeqModel

const CardFilterForm: React.FC = () => {
  const { router, query, pathname } = useURL<CardSearchParams>();

  //SearchParams Variables
  const limit = query["limit"] || DEFAULT_LIMIT;

  const defaultFilters = DEFAULT_FILTERS;
  const initialValues: CardFormikFilter = getFilterValueFromURL(
    query,
    defaultFilters
  );

  //Tanstack queries
  //Generated by GetRequiredQueryFromTanstackBySeqModel

  //Zustand stores
  const [setPage, setLastPage, setFetchCount, resetRowSelection] = useCardStore(
    (state) => [
      state.setPage,
      state.setLastPage,
      state.setFetchCount,
      state.resetRowSelection,
    ]
  );

  const handleFormikSubmit = (
    values: Partial<CardFormikFilter>,
    formik: FormikHelpers<CardFormikFilter>
  ) => {
    const params = {
      ...query,
      ...(getParamsObject(values, defaultFilters) as Partial<CardSearchParams>),
    };

    const newURL = `${pathname}?${encodeParams(params)}`;
    router.push(newURL);
    setFetchCount(true);
    setPage(1);
    setLastPage(1);
    resetRowSelection();
  };

  const handleLimitChange = (value: string) => {
    const params = { ...query, limit: value };
    const newURL = `${pathname}?${encodeParams(params)}`;
    router.push(newURL);
    resetRowSelection();
  };

  const renderFormik = (formik: FormikProps<CardFormikFilter>) => {
    const filtered = isEqual(defaultFilters, formik.values);

    const handleSubmitClick: MouseEventHandler = (e) => {
      e.preventDefault();
      formik.submitForm();
    };

    const handleClearClick: MouseEventHandler = (e) => {
      e.preventDefault();
      formik.setValues(defaultFilters as CardFormikFilter);
      formik.submitForm();
    };

    return (
      <Form
        className="flex gap-4"
        autoComplete="off"
      >
        {/* Generated by GetFormikFilterQControl */}
        <FormikControl
          name="q"
          placeholder="Filter Cards..."
          type="Text"
          containerClassNames={["min-w-[200px]"]}
        />
        {/* Generated by GetAllFormikFilterControlBySeqModel */}
        <Button
          type="button"
          onClick={handleSubmitClick}
          size={"sm"}
          variant={"secondary"}
        >
          Search
        </Button>
        <Button
          type="button"
          size={"sm"}
          variant={"ghost"}
          disabled={filtered}
          onClick={handleClearClick}
        >
          Clear
        </Button>
      </Form>
    );
  };

  return (
    <div className="flex justify-between w-full">
      <Formik
        initialValues={initialValues}
        onSubmit={handleFormikSubmit}
      >
        {renderFormik}
      </Formik>
      <LimitSelector
        handleLimitChange={handleLimitChange}
        value={limit}
      />
    </div>
  );
};

export default CardFilterForm;
