//Generated by WriteToModellibs_ts - ModelLibs.ts
import { LockedDeckFormikShape } from "@/interfaces/LockedDeckInterfaces";
import { LockedDeck } from "@/models/LockedDeckModel";
import { Op } from "sequelize";
import { Transaction } from "sequelize";

//Reusable functions
export const createLockedDeck = async (
  lockedDeck: Omit<LockedDeckFormikShape, "touched" | "index">,
  t: Transaction
) => {
  return await LockedDeck.create(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
      name: lockedDeck.name!,
    },
    { transaction: t }
  );
};

export const updateLockedDeck = async (
  lockedDeck: Omit<LockedDeckFormikShape, "touched" | "index">,
  primaryKey: keyof Omit<LockedDeckFormikShape, "touched" | "index">,
  t: Transaction,
  primaryKeyValue?: string | number
) => {
  await LockedDeck.update(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
      name: lockedDeck.name!,
    },
    {
      where: { [primaryKey]: primaryKeyValue || lockedDeck[primaryKey] },
      transaction: t,
      individualHooks: true,
    }
  );
};

export const deleteLockedDecks = async (
  primaryKey: keyof Omit<LockedDeckFormikShape, "touched">,
  deletedIds: string[] | number[],
  t: Transaction
) => {
  await LockedDeck.destroy({
    where: { [primaryKey]: { [Op.in]: deletedIds } },
    transaction: t,
  });
};
