import Footer from "@/components/Footer";
import Header from "@/components/header/Header";
import "./globals.css";
import { Roboto_Flex } from "next/font/google";
import ClientProviders from "@/components/ClientProviders";
import SessionButton from "@/components/header/SessionButton";
import Providers from "@/components/ThemeProvider";

const inter = Roboto_Flex({
  subsets: ["latin"],
  display: "swap",
  fallback: ["system-ui", "arial"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.className} dark`}
    >
      <body className="flex flex-col w-full min-h-screen">
        <Providers>
          <ClientProviders>
            <Header sessionButton={<SessionButton />} />
            {children}
            <Footer />
          </ClientProviders>
        </Providers>
      </body>
    </html>
  );
}
