//Generated by WriteToModelsRouteApi - models route next 13
import { Hero } from "@/models/HeroModel";
import { FindOptions, Transaction } from "sequelize";
import { cloneDeep } from "lodash";
import {
  checkDuplicateCombinations,
  formatSortAsSequelize,
  getSort,
  parseParams,
  returnJSONResponse,
} from "@/utils/utils";
import { genericGetAll } from "@/utils/generic";
import sequelize from "@/config/db";
import handleSequelizeError from "@/utils/errorHandling";
import { Op } from "sequelize";
import {
  HeroDeletePayload,
  HeroFormUpdatePayload,
  HeroFormikShape,
  HeroSearchParams,
  HeroUpdatePayload,
} from "@/interfaces/HeroInterfaces";
import { NextResponse } from "next/server";
import { DEFAULT_LIMIT } from "@/utils/constants";
import {
  DEFAULT_SORT_BY,
  PRIMARY_KEY,
  REQUIRED_FIELDS,
  UNIQUE_FIELDS
} from "@/utils/constants/HeroConstants";
import { HeroSchema } from "@/schema/HeroSchema";
import { appendAndFilters, getCursor } from "@/utils/api/utils";

//Generated by GetAllRelatedLeftModelImportRoute
//Generated by GetRelatedLeftModelImportRoute - GetRelatedLeftModelImportRoute
import {
  createHeroSkill,
  updateHeroSkill,
} from "@/app/api/hero-skills/route";
import { HeroSkillSchema } from "@/schema/HeroSkillSchema";
import { PRIMARY_KEY as HEROSKILL_PRIMARY_KEY } from "@/utils/constants/HeroSkillConstants";

const ModelObject = Hero;

//Generated by GeneratefindOptions
const findOptions: FindOptions<typeof Hero> = {
  //Generated by GenerateIncludeOption
  include: [],
  //Generated by GenerateAttributesOption
  attributes: [//Generated by GetAllModelAttributesBySeqModel
"belongsto_id"],
};

//Reusable functions
export const createHero = async (
  hero: Omit<HeroFormikShape, "touched" | "index">,
  t: Transaction
) => {
  return await Hero.create(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel

    },
    { transaction: t }
  );
};

export const updateHero = async (
  hero: Omit<HeroFormikShape, "touched" | "index">,
  primaryKey: keyof Omit<HeroFormikShape, "touched" | "index">,
  t: Transaction,
  primaryKeyValue?: string | number
) => {
  await Hero.update(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel

    },
    {
      where: { [primaryKey]: primaryKeyValue || hero[primaryKey] },
      transaction: t,
      individualHooks: true,
    }
  );
};

export const deleteHeroes = async (
  primaryKey: keyof Omit<HeroFormikShape, "touched">,
  deletedIds: string[] | number[],
  t: Transaction
) => {
  await Hero.destroy({
    where: { [primaryKey]: { [Op.in]: deletedIds } },
    transaction: t,
  });
};

//Generated by Generate_getModelsSimpleFilterNext13
export const GET = async (req: Request) => {
  //Generated by Generate_findOptionsCopy
  const findOptionsCopy: FindOptions<typeof Hero> = cloneDeep(findOptions);
  const heroAttributes = Object.keys(Hero.getAttributes()).map(
    (attribute) => attribute
  );

  const searchParams = new URL(req.url).searchParams;

  const query = parseParams(searchParams) as Partial<HeroSearchParams>;
  const primaryKey = PRIMARY_KEY;

  const simpleOnly = query["simpleOnly"];
  const cursor = query["cursor"];
  const fetchCount = query["fetchCount"] === "true";

  let limit = query["limit"];
  const sort = query["sort"]
    ? heroAttributes.includes(query["sort"]) ||
      heroAttributes.includes(query["sort"].substring(1))
      ? query["sort"]
      : DEFAULT_SORT_BY
    : DEFAULT_SORT_BY;

  //Remove the - from the sort parameter
  const sortField = sort.includes("-") ? sort.substring(1) : sort;


  if (!simpleOnly) {
    const where: Record<string | symbol, unknown> = { [Op.and]: [] };
    const andFilters = [];

    const q = query["q"];

    if (q) {
      andFilters.push({
        [Op.or]: [
          //Generated by GetAllQFilterFieldBySeqModel

        ],
      });
    }

    //Generated by GetAllBackendFiltersBySeqModel


    //get all the count here first
    let recordCount = 0;
    if (fetchCount) {
      recordCount = await Hero.count({
        where: { [Op.and]: andFilters },
      });
    }

    if (cursor) {
      appendAndFilters(andFilters, sort, sortField, primaryKey, cursor);
    }

    where[Op.and] = andFilters;
    findOptionsCopy.where = where;
    limit = limit || DEFAULT_LIMIT;
    findOptionsCopy.limit = parseInt(limit);

    //@ts-ignore
    findOptionsCopy.order = formatSortAsSequelize(
      getSort(sort, DEFAULT_SORT_BY, primaryKey)
    );

    try {
      const data = await Hero.findAll(findOptionsCopy);

      const cursor = getCursor(data, sortField, primaryKey);

      return NextResponse.json({
        rows: data,
        cursor,
        ...(fetchCount && { count: recordCount }),
      });
    } catch (err) {
      return handleSequelizeError(err);
    }
  } else {
    return genericGetAll(ModelObject, findOptionsCopy);
  }
};

//Generated by GetMultiCreateModelPOSTRoute - GetMultiCreateModelPOSTRoute
export const POST = async (req: Request) => {
  const body = (await req.json()) as HeroUpdatePayload;
  const { Heroes } = body;

  //Generated by GenerateUniquenessValidation
  //Validate record uniqueness

  UNIQUE_FIELDS.forEach((item) => {
    const uniquenessError = checkDuplicateCombinations(item, Heroes);

    if (uniquenessError) {
      return returnJSONResponse({
        status: "error",
        error: uniquenessError,
        errorCode: 422,
      });
    }
  });

  const t = await sequelize.transaction();
  let recordsCreated = 0;

  for (const item of Heroes) {
    try {
      await HeroSchema.validate(item);
    } catch (error) {
      return handleSequelizeError(error);
    }
  }

  try {
    for (const item of Heroes) {
      if (item[PRIMARY_KEY] === "") {
        await createHero(item, t);
        recordsCreated++;
      } else {
        await updateHero(item, PRIMARY_KEY, t);
      }
    }

    await t.commit();

    return NextResponse.json({
      recordsCreated,
    });
  } catch (err) {
    await t.rollback();
    return handleSequelizeError(err);
  }
};


export const DELETE = async (req: Request) => {
  const body = (await req.json()) as HeroDeletePayload;
  const { deletedHeroes } = body;

  if (deletedHeroes.length > 0) {
    const t = await sequelize.transaction();
    try {
      await deleteHeroes(PRIMARY_KEY, deletedHeroes, t);
      t.commit();
      return NextResponse.json("success");
    } catch (error) {
      t.rollback();
      return handleSequelizeError(error);
    }
  }
};
