//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import CardKeywordFilterForm from "@/components/card-keywords/CardKeywordFilterForm";
import CardKeywordTable from "@/components/card-keywords/CardKeywordTable";

export const metadata = {
  title: "Card Keywords",
};

const CardKeywords: React.FC = () => {
  return (
    <div className="flex flex-col flex-1 w-full px-4 mx-auto text-sm lg:px-0 main-height-less-footer">
      <div className="flex flex-col flex-1 w-full gap-4 p-4 mx-auto border rounded-sm border-border">
        <h1 className="text-2xl font-bold">Card Keywords</h1>
        <div className="flex">
          <CardKeywordFilterForm />
        </div>
        <div className="flex flex-col flex-1 ">
          <CardKeywordTable />
        </div>
      </div>
    </div>
  );
};

export default CardKeywords;
