//Generated by GetuseModelListts - useModelList.ts
"use client";
import { GetCardsResponse } from "@/interfaces/CardInterfaces";
import { CardSearchParams } from "@/interfaces/CardInterfaces";
import { BasicModel } from "@/interfaces/GeneralInterfaces";
import axiosClient from "@/utils/api";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";

const getCards = async (useName: boolean = false) => {
  const { data } = await axiosClient.get<GetCardsResponse>(`cards`, {
    params: {
      fetchCount: "false",
      simpleOnly: "true",
    } as Partial<CardSearchParams>,
  });

  return data.rows.map((item) => ({
    ...item,
    id: !useName ? item.id : item.name,
    name: item.name,
  }));
};

interface UseListProps {
  placeholderData?: BasicModel[];
  useName?: boolean;
}

const useCardList = (prop?: UseListProps) => {
  //local states
  const [mounted, setMounted] = useState(false);

  const _ = useQuery({
    queryKey: ["card-list"],
    queryFn: () => getCards(prop?.useName),
    enabled: mounted,
    placeholderData: prop?.placeholderData,
  });

  useEffect(() => {
    setMounted(true);
  }, []);

  return _;
};

export default useCardList;
