//Generated by WriteToModelsRouteApi - models route next 13
import { Card } from "@/models/CardModel";
import { FindOptions, Transaction } from "sequelize";
import { cloneDeep } from "lodash";
import {
  checkDuplicateCombinations,
  formatSortAsSequelize,
  getSort,
  parseParams,
  returnJSONResponse,
} from "@/utils/utils";
import { genericGetAll } from "@/utils/generic";
import sequelize from "@/config/db";
import handleSequelizeError from "@/utils/errorHandling";
import { Op } from "sequelize";
import {
  CardDeletePayload,
  CardFormikShape,
  CardSearchParams,
  CardUpdatePayload,
} from "@/interfaces/CardInterfaces";
import { NextResponse } from "next/server";
import { DEFAULT_LIMIT } from "@/utils/constants";
import {
  DEFAULT_SORT_BY,
  PRIMARY_KEY,
  REQUIRED_FIELDS,
  UNIQUE_FIELDS,
} from "@/utils/constants/CardConstants";
import { CardSchema } from "@/schema/CardSchema";
import { appendAndFilters, getCursor } from "@/utils/api/utils";

const ModelObject = Card;

//Generated by GeneratefindOptions
const findOptions: FindOptions<typeof Card> = {
  //Generated by GenerateIncludeOption
  include: [],
  //Generated by GenerateAttributesOption
  attributes: [
    //Generated by GetAllModelAttributesBySeqModel
    "id",
    "name",
    "type",
    "cost",
    "battleStyle",
    "atk",
    "shield",
    "description",
    "deckId",
    "slug",
  ],
};

//Reusable functions
export const createCard = async (
  card: Omit<CardFormikShape, "touched">,
  t: Transaction
) => {
  return await Card.create(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
      name: card.name!,
      type: card.type!,
      cost: parseInt(card.cost as string),
      battleStyle: card.battleStyle ? card.battleStyle! : null,
      atk: card.atk ? parseInt(card.atk as string) : null,
      shield: card.shield ? parseInt(card.shield as string) : null,
      description: card.description ? card.description! : null,
      deckId: parseInt(card.deckId as string),
    },
    { transaction: t }
  );
};

export const updateCard = async (
  card: Omit<CardFormikShape, "touched" | "index">,
  primaryKey: keyof Omit<CardFormikShape, "touched" | "index">,
  t: Transaction,
  primaryKeyValue?: string | number
) => {
  await Card.update(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
      name: card.name!,
      type: card.type!,
      cost: parseInt(card.cost as string),
      battleStyle: card.battleStyle ? card.battleStyle! : null,
      atk: card.atk ? parseInt(card.atk as string) : null,
      shield: card.shield ? parseInt(card.shield as string) : null,
      description: card.description ? card.description! : null,
      deckId: parseInt(card.deckId as string),
    },
    {
      where: { [primaryKey]: primaryKeyValue || card[primaryKey] },
      transaction: t,
      individualHooks: true,
    }
  );
};

export const deleteCards = async (
  primaryKey: keyof Omit<CardFormikShape, "touched">,
  deletedIds: string[] | number[],
  t: Transaction
) => {
  await Card.destroy({
    where: { [primaryKey]: { [Op.in]: deletedIds } },
    transaction: t,
  });
};

//Generated by Generate_getModelsSimpleFilterNext13
export const GET = async (req: Request) => {
  //Generated by Generate_findOptionsCopy
  const findOptionsCopy: FindOptions<typeof Card> = cloneDeep(findOptions);
  const cardAttributes = Object.keys(Card.getAttributes()).map(
    (attribute) => attribute
  );

  const searchParams = new URL(req.url).searchParams;

  const query = parseParams(searchParams) as Partial<CardSearchParams>;
  const primaryKey = PRIMARY_KEY;

  const simpleOnly = query["simpleOnly"];
  const cursor = query["cursor"];
  const fetchCount = query["fetchCount"] === "true";

  let limit = query["limit"];
  const sort = query["sort"]
    ? cardAttributes.includes(query["sort"]) ||
      cardAttributes.includes(query["sort"].substring(1))
      ? query["sort"]
      : DEFAULT_SORT_BY
    : DEFAULT_SORT_BY;

  //Remove the - from the sort parameter
  const sortField = sort.includes("-") ? sort.substring(1) : sort;

  if (!simpleOnly) {
    const where: Record<string | symbol, unknown> = { [Op.and]: [] };
    const andFilters = [];

    const q = query["q"];

    if (q) {
      andFilters.push({
        [Op.or]: [
          //Generated by GetAllQFilterFieldBySeqModel
          //Generated by GenerateAQFilterField - GenerateAQFilterField
          { name: { [Op.like]: `%${q}%` } }, //Generated by GenerateAQFilterField - GenerateAQFilterField
          { description: { [Op.like]: `%${q}%` } },
        ],
      });
    }

    //Generated by GetAllBackendFiltersBySeqModel

    //get all the count here first
    let recordCount = 0;
    if (fetchCount) {
      recordCount = await Card.count({
        where: { [Op.and]: andFilters },
      });
    }

    if (cursor) {
      appendAndFilters(andFilters, sort, sortField, primaryKey, cursor);
    }

    where[Op.and] = andFilters;
    findOptionsCopy.where = where;
    limit = limit || DEFAULT_LIMIT;
    findOptionsCopy.limit = parseInt(limit);

    //@ts-ignore
    findOptionsCopy.order = formatSortAsSequelize(
      getSort(sort, DEFAULT_SORT_BY, primaryKey)
    );

    try {
      const data = await Card.findAll(findOptionsCopy);

      const cursor = getCursor(data, sortField, primaryKey);

      return NextResponse.json({
        rows: data,
        cursor,
        ...(fetchCount && { count: recordCount }),
      });
    } catch (err) {
      return handleSequelizeError(err);
    }
  } else {
    return genericGetAll(ModelObject, findOptionsCopy);
  }
};

export const POST = async (req: Request) => {
  const body = (await req.json()) as CardUpdatePayload;
  const { Cards } = body;

  //Generated by GenerateUniquenessValidation
  //Validate record uniqueness

  UNIQUE_FIELDS.forEach((item) => {
    const uniquenessError = checkDuplicateCombinations(item, Cards);

    if (uniquenessError) {
      return returnJSONResponse({
        status: "error",
        error: uniquenessError,
        errorCode: 422,
      });
    }
  });

  const t = await sequelize.transaction();
  let recordsCreated = 0;

  for (const item of Cards) {
    try {
      await CardSchema.validate(item);
    } catch (error) {
      return handleSequelizeError(error);
    }
  }

  try {
    for (const item of Cards) {
      if (item[PRIMARY_KEY] === "") {
        await createCard(item, t);
        recordsCreated++;
      } else {
        await updateCard(item, PRIMARY_KEY, t);
      }
    }

    await t.commit();

    return NextResponse.json({
      recordsCreated,
    });
  } catch (err) {
    await t.rollback();
    return handleSequelizeError(err);
  }
};

export const DELETE = async (req: Request) => {
  const body = (await req.json()) as CardDeletePayload;
  const { deletedCards } = body;

  if (deletedCards.length > 0) {
    const t = await sequelize.transaction();
    try {
      await deleteCards(PRIMARY_KEY, deletedCards, t);
      t.commit();
      return NextResponse.json("success");
    } catch (error) {
      t.rollback();
      return handleSequelizeError(error);
    }
  }
};
