//Generated by GetuseModelListts - useModelList.ts
"use client";
import { GetDecksResponse } from "@/interfaces/DeckInterfaces";
import { DeckSearchParams } from "@/interfaces/DeckInterfaces";
import { BasicModel } from "@/interfaces/GeneralInterfaces";
import axiosClient from "@/utils/api";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";

const getDecks = async (useName: boolean = false) => {
  const { data } = await axiosClient.get<GetDecksResponse>(`decks`, {
    params: {
      fetchCount: "false",
      simpleOnly: "true",
    } as Partial<DeckSearchParams>,
  });

  return data.rows.map((item) => ({
    id: !useName ? item.id : item.name,
    name: item.name,
  }));
};

interface UseListProps {
  placeholderData?: BasicModel[];
  useName?: boolean;
}

const useDeckList = (prop?: UseListProps) => {
  //local states
  const [mounted, setMounted] = useState(false);

  const _ = useQuery({
    queryKey: ["deck-list"],
    queryFn: () => getDecks(prop?.useName),
    enabled: mounted,
    placeholderData: prop?.placeholderData,
  });

  useEffect(() => {
    setMounted(true);
  }, []);

  return _;
};

export default useDeckList;
