//Generated by GetuseModelListts - useModelList.ts
"use client";
import { GetDecksResponse } from "@/interfaces/DeckInterfaces";
import { DeckSearchParams } from "@/interfaces/DeckInterfaces";
import axiosClient from "@/utils/api";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";

const getDecks = async () => {
  const { data } = await axiosClient.get<GetDecksResponse>(`decks`, {
    params: {
      fetchCount: "false",
      simpleOnly: "true",
    } as Partial<DeckSearchParams>,
  });

  return data.rows.map((item) => ({
    id: item.id,
    name: item.name,
  }));
};

const useDeckList = () => {
  //local states
  const [mounted, setMounted] = useState(false);

  const _ = useQuery({
    queryKey: ["deck-list"],
    queryFn: getDecks,
    enabled: mounted,
  });

  useEffect(() => {
    setMounted(true);
  }, []);

  return _;
};

export default useDeckList;
