//Generated by WriteToModelinterface_ts
import { ListQuery } from "./interface";

export interface CardKeywordModel {
  //Generated by GetAllModelFieldTypeBySeqModel
id: number | string;name: string;slug: string;
}

export interface CardKeywordFormikShape extends Omit<CardKeywordModel, "slug" | "createdAt" | "updatedAt"> {
  touched: boolean;
}

export interface CardKeywordFormikInitialValues {
  CardKeywords: CardKeywordFormikShape[];
}

export interface CardKeywordUpdatePayload {
  CardKeywords: Partial<Omit<CardKeywordFormikShape, "touched">>[];
  deletedCardKeywords: number[] | string[];
}

export interface CardKeywordFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
}

export interface CardKeywordSearchParams
  extends ListQuery,
    Omit<CardKeywordFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetCardKeywordsResponse {
  count: number;
  rows: CardKeywordModel[];
  cursor: string;
}
