//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13
//Generated by GetAllRelatedInterfaceImportBySeqModel
//Generated by GetRelatedInterfaceImport - RelatedInterfaceImport
import {
  CardCardKeywordFormikInitialValues,
  CardCardKeywordFormikShape,
  CardCardKeywordModel,
  CardCardKeywordUpdatePayload,
} from "@/interfaces/CardCardKeywordInterfaces";

import { ListQuery } from "./interface";

export interface CardKeywordModel {
  //Generated by GetAllModelFieldTypeBySeqModel
  id: number | string; //Generated by GetModelFieldType
  name: string; //Generated by GetModelFieldType
  slug: string;
  //Generated by GetAllChildModelInterfaceBySeqModel
  CardCardKeywords: CardCardKeywordModel[]; //Generated by GetChildModelInterface - ChildModelInterface
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface CardKeywordFormikShape
  extends Omit<
    CardKeywordModel,
    "slug" | "createdAt" | "updatedAt" | "CardCardKeywords" //Generated by GetRelatedPluralizedModelName - RelatedPluralizedModelName
  > {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface CardKeywordFormikInitialValues {
  CardKeywords: CardKeywordFormikShape[];
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface CardKeywordFormFormikInitialValues
  extends Omit<CardKeywordFormikShape, "touched" | "index">,
    CardCardKeywordFormikInitialValues {}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface CardKeywordUpdatePayload
  extends Partial<CardCardKeywordUpdatePayload> {
  CardKeywords: Omit<CardKeywordFormikShape, "touched">[];
}

export interface CardKeywordDeletePayload {
  deletedCardKeywords: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface CardKeywordFormUpdatePayload
  extends Omit<CardKeywordFormikShape, "touched" | "index">,
    CardCardKeywordUpdatePayload {}

export interface CardKeywordFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
  q: string;
}

export interface CardKeywordSearchParams
  extends ListQuery,
    Omit<CardKeywordFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes
}

export interface GetCardKeywordsResponse {
  count: number;
  rows: CardKeywordModel[];
  cursor: string;
}
