//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13

//Generated by GetAllRelatedRightModelImport
import { DeckModel } from "@/interfaces/DeckInterfaces"; //Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { ListQuery } from "./interface";

export interface CardModel {
  //Generated by GetAllModelFieldTypeBySeqModel
  id: number | string; //Generated by GetModelFieldType
  name: string; //Generated by GetModelFieldType
  type: "Character" | "Weapon" | "Power" | "Tactic"; //Generated by GetModelFieldType
  cost: number | string; //Generated by GetModelFieldType
  battleStyle?: "Support" | "Attack" | "Guardian"; //Generated by GetModelFieldType
  atk?: number | string; //Generated by GetModelFieldType
  shield?: number | string; //Generated by GetModelFieldType
  description?: string; //Generated by GetModelFieldType
  deckId: number | string; //Generated by GetModelFieldType
  slug: string;

  //Generated by GetAllRelatedRightModelInterface
  Deck: DeckModel; //Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface CardFormikShape
  extends Omit<CardModel, "slug" | "createdAt" | "updatedAt"> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface CardFormikInitialValues {
  Cards: CardFormikShape[];
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface CardFormFormikInitialValues
  extends Omit<CardFormikShape, "touched" | "index"> {}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface CardUpdatePayload {
  Cards: Omit<CardFormikShape, "touched">[];
}

export interface CardDeletePayload {
  deletedCards: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface CardFormUpdatePayload
  extends Omit<CardFormikShape, "touched" | "index"> {}

export interface CardFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
  q: string;
}

export interface CardSearchParams
  extends ListQuery,
    Omit<CardFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes
}

export interface GetCardsResponse {
  count: number;
  rows: CardModel[];
  cursor: string;
}
