//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13

import { ListQuery } from "./interface";

export interface CardSkillModel {
  //Generated by GetAllModelFieldTypeBySeqModel
  id: number | string; //Generated by GetModelFieldType
  name: string; //Generated by GetModelFieldType
  description: string; //Generated by GetModelFieldType
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface CardSkillFormikShape
  extends Omit<CardSkillModel, "slug" | "createdAt" | "updatedAt"> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface CardSkillFormikInitialValues {
  CardSkills: CardSkillFormikShape[];
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface CardSkillFormFormikInitialValues
  extends Omit<CardSkillFormikShape, "touched" | "index"> {}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface CardSkillUpdatePayload {
  CardSkills: Omit<CardSkillFormikShape, "touched">[];
}

export interface CardSkillDeletePayload {
  deletedCardSkills: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface CardSkillFormUpdatePayload
  extends Omit<CardSkillFormikShape, "touched" | "index"> {}

export interface CardSkillFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
  q: string;
}

export interface CardSkillSearchParams
  extends ListQuery,
    Omit<CardSkillFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes
}

export interface GetCardSkillsResponse {
  count: number;
  rows: CardSkillModel[];
  cursor: string;
}
