//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13
//Generated by GetAllRelatedInterfaceImportBySeqModel
//Generated by GetRelatedInterfaceImport - RelatedInterfaceImport
import { HeroModel } from "@/interfaces/HeroInterfaces"; //Generated by GetRelatedInterfaceImport - RelatedInterfaceImport
import {
  HeroSkillFormikInitialValues,
  HeroSkillModel,
  HeroSkillUpdatePayload,
} from "@/interfaces/HeroSkillInterfaces";
import { ListQuery } from "./interface";

export interface DeckModel {
  //Generated by GetAllModelFieldTypeBySeqModel
  id: number | string; //Generated by GetModelFieldType
  name: string; //Generated by GetModelFieldType
  is_hero: boolean; //Generated by GetModelFieldType
  slug: string;
  createdAt: string;
  updatedAt: string;
  //Generated by GetAllChildModelInterfaceBySeqModel
  HeroSkills: HeroSkillModel[]; //Generated by GetChildModelInterface - ChildModelInterface
  //Generated by GetAllParentModelInterfaceBySeqModel
  Hero: HeroModel; //Generated by GetParentModelInterface - ParentModelInterface
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface DeckFormikShape
  extends Omit<
    DeckModel,
    "slug" | "createdAt" | "updatedAt" | "HeroSkills" | "Hero"
  > {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface DeckFormikInitialValues {
  Decks: DeckFormikShape[];
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface DeckFormFormikInitialValues
  extends Omit<DeckFormikShape, "touched" | "index">,
    HeroSkillFormikInitialValues {}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface DeckUpdatePayload extends Partial<HeroSkillUpdatePayload> {
  Decks: Omit<DeckFormikShape, "touched">[];
}

export interface DeckDeletePayload {
  deletedDecks: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface DeckFormUpdatePayload
  extends Omit<DeckFormikShape, "touched">,
    HeroSkillUpdatePayload {}

export interface DeckFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
  q: string;
  is_hero: boolean; //Generated by GetThisFilterInterface
}

export interface DeckSearchParams
  extends ListQuery,
    Omit<
      DeckFormikFilter, //Generated by GetAllNonStringFilterNames
      "is_hero"
    > {
  //Generated by GetAllNonStringFilterTypes
  is_hero: string; //Generated by GetThisFilterInterface
}

export interface GetDecksResponse {
  count: number;
  rows: DeckModel[];
  cursor: string;
}
