//Generated by WriteToModelinterface_ts
import { ListQuery } from "./interface";

export interface HeroModel {
  //Generated by GetAllModelFieldTypeBySeqModel
  belongsto_id: number | string;
  heroName: string;
}

export interface HeroFormikShape
  extends Omit<HeroModel, "slug" | "createdAt" | "updatedAt"> {
  touched: boolean;
}

export interface HeroFormikInitialValues {
  Heroes: HeroFormikShape[];
}

export interface HeroUpdatePayload {
  Heroes: Partial<Omit<HeroFormikShape, "touched">>[];
  deletedHeroes: number[] | string[];
}

export interface HeroFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
}

export interface HeroSearchParams
  extends ListQuery,
    Omit<HeroFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes
}

export interface GetHeroesResponse {
  count: number;
  rows: HeroModel[];
  cursor: string;
}
