//Generated by WriteToModelinterface_ts
import { ListQuery } from "./interface";

export interface HeroSkillModel {
  //Generated by GetAllModelFieldTypeBySeqModel
id: number | string;name: string;type: string;cost: number;description: string;heroId: number;
}

export interface HeroSkillFormikShape extends Omit<HeroSkillModel, "slug" | "createdAt" | "updatedAt"> {
  touched: boolean;
}

export interface HeroSkillFormikInitialValues {
  HeroSkills: HeroSkillFormikShape[];
}

export interface HeroSkillUpdatePayload {
  HeroSkills: Partial<Omit<HeroSkillFormikShape, "touched">>[];
  deletedHeroSkills: number[] | string[];
}

export interface HeroSkillFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
}

export interface HeroSkillSearchParams
  extends ListQuery,
    Omit<HeroSkillFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetHeroSkillsResponse {
  count: number;
  rows: HeroSkillModel[];
  cursor: string;
}
