//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13

//Generated by GetAllRelatedRightModelImport
import { HeroModel } from "@/interfaces/HeroInterfaces"; //Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { DeckModel } from "@/interfaces/DeckInterfaces"; //Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { ListQuery } from "./interface";

export interface HeroSkillModel {
  //Generated by GetAllModelFieldTypeBySeqModel
  id: number | string; //Generated by GetModelFieldType
  name: string; //Generated by GetModelFieldType
  type: "Active" | "Passive"; //Generated by GetModelFieldType
  cost: number | string | null; //Generated by GetModelFieldType
  description: string; //Generated by GetModelFieldType
  heroId: number | string; //Generated by GetModelFieldType

  //Generated by GetAllRelatedRightModelInterface
  Hero: HeroModel; //Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
  Deck: DeckModel; //Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface HeroSkillFormikShape
  extends Omit<
    HeroSkillModel,
    | "slug"
    | "createdAt"
    | "updatedAt"
    | "Hero" //Generated by GetRelatedRightModelName - GetRelatedRightModelName
    | "Deck" //Generated by GetRelatedRightModelName - GetRelatedRightModelName
  > {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface HeroSkillFormikInitialValues {
  HeroSkills: HeroSkillFormikShape[];
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface HeroSkillFormFormikInitialValues
  extends Omit<HeroSkillFormikShape, "touched" | "index"> {}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface HeroSkillUpdatePayload {
  HeroSkills: Omit<HeroSkillFormikShape, "touched">[];
}

export interface HeroSkillDeletePayload {
  deletedHeroSkills: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface HeroSkillFormUpdatePayload
  extends Omit<HeroSkillFormikShape, "touched" | "index"> {}

export interface HeroSkillFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
  q: string;
  type: string; //Generated by GetThisFilterInterface
  hero: string[]; //Generated by GetThisFilterInterface
}

export interface HeroSkillSearchParams
  extends ListQuery,
    Omit<
      HeroSkillFormikFilter, //Generated by GetAllNonStringFilterNames
      "hero"
    > {
  //Generated by GetAllNonStringFilterTypes
  hero: string; //Generated by GetThisFilterInterface
}

export interface GetHeroSkillsResponse {
  count: number;
  rows: HeroSkillModel[];
  cursor: string;
}
