//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13
//Generated by GetAllRelatedInterfaceImportBySeqModel
//Generated by GetRelatedInterfaceImport - RelatedInterfaceImport
import { LockedDeckCardFormikInitialValues, LockedDeckCardFormikShape,LockedDeckCardModel,LockedDeckCardUpdatePayload } from "@/interfaces/LockedDeckCardInterfaces";

import { ListQuery } from "./interface";

export interface LockedDeckModel {
  //Generated by GetAllModelFieldTypeBySeqModel
id: number | string;//Generated by GetModelFieldType
name: string;//Generated by GetModelFieldType
slug: string;
  //Generated by GetAllChildModelInterfaceBySeqModel
LockedDeckCards: LockedDeckCardModel[];//Generated by GetChildModelInterface - ChildModelInterface
  
  
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface LockedDeckFormikShape extends Omit<LockedDeckModel, "slug" | "createdAt" | "updatedAt" 
| "LockedDeckCards"//Generated by GetRelatedPluralizedModelName - RelatedPluralizedModelName 
> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface LockedDeckFormikInitialValues {
  LockedDecks: LockedDeckFormikShape[];
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface LockedDeckFormFormikInitialValues
  extends Omit<LockedDeckFormikShape, "touched" | "index"> ,LockedDeckCardFormikInitialValues{
  
}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface LockedDeckUpdatePayload extends Partial<LockedDeckCardUpdatePayload> {
  LockedDecks: Omit<LockedDeckFormikShape, "touched">[];
}

export interface LockedDeckDeletePayload {
  deletedLockedDecks: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface LockedDeckFormUpdatePayload
  extends Omit<LockedDeckFormikShape, "touched" | "index" 
> 
//Generated by GetAllRelatedModelUpdatePayload
,LockedDeckCardUpdatePayload,//Generated by GetModelUpdatePayload - ModelUpdatePayload 
{
  
}

export interface LockedDeckFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
}

export interface LockedDeckSearchParams
  extends ListQuery,
    Omit<LockedDeckFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetLockedDecksResponse {
  count: number;
  rows: LockedDeckModel[];
  cursor: string;
}
