//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13

//Generated by GetAllRelatedRightModelImport
import { CardModel } from "@/interfaces/CardInterfaces"; //Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { LockedDeckModel } from "@/interfaces/LockedDeckInterfaces"; //Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { ListQuery } from "./interface";

export interface LockedDeckCardModel {
  //Generated by GetAllModelFieldTypeBySeqModel
  id: number | string; //Generated by GetModelFieldType
  lockedDeckId: number | string; //Generated by GetModelFieldType
  cardId: number | string; //Generated by GetModelFieldType

  //Generated by GetAllRelatedRightModelInterface
  Card: CardModel; //Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
  LockedDeck: LockedDeckModel; //Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface LockedDeckCardFormikShape
  extends Omit<
    LockedDeckCardModel,
    | "slug"
    | "createdAt"
    | "updatedAt"
    | "Card" //Generated by GetRelatedRightModelName - GetRelatedRightModelName
    | "LockedDeck" //Generated by GetRelatedRightModelName - GetRelatedRightModelName
  > {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface LockedDeckCardFormikInitialValues {
  LockedDeckCards: LockedDeckCardFormikShape[];
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface LockedDeckCardFormFormikInitialValues
  extends Omit<LockedDeckCardFormikShape, "touched" | "index"> {}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface LockedDeckCardUpdatePayload {
  LockedDeckCards: Omit<LockedDeckCardFormikShape, "touched">[];
}

export interface LockedDeckCardDeletePayload {
  deletedLockedDeckCards: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface LockedDeckCardFormUpdatePayload
  extends Omit<LockedDeckCardFormikShape, "touched" | "index"> {}

export interface LockedDeckCardFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
}

export interface LockedDeckCardSearchParams
  extends ListQuery,
    Omit<LockedDeckCardFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes
}

export interface GetLockedDeckCardsResponse {
  count: number;
  rows: LockedDeckCardModel[];
  cursor: string;
}
