//Generated by WriteToUsemodeldeletedialog_ts
import { HeroSkillUpdatePayload } from "@/interfaces/HeroSkillInterfaces";
import { create } from "zustand";

type State = {
  recordsToDelete: string[];
  setRecordsToDelete: (recordsToDelete: string[]) => void;
  isDialogLoading: boolean;
  setIsDialogLoading: (isDialogLoading: boolean) => void;
  mutate?: (payload: HeroSkillUpdatePayload) => void;
  setMutate: (mutate: (payload: HeroSkillUpdatePayload) => void) => void;
};

// Create your store, which includes both state and (optionally) actions
const useHeroSkillDeleteDialog = create<State>((set) => ({
  recordsToDelete: [],
  setRecordsToDelete: (recordsToDelete) => set({ recordsToDelete }),
  isDialogLoading: false,
  setIsDialogLoading: (isDialogLoading) => set({ isDialogLoading }),
  setMutate: (mutate) => set({ mutate }),
}));

export { useHeroSkillDeleteDialog };
