//Generated by ImportCompleteModelFile
//Generated by GetCompleteModelFile

//Generated by GetModelImports
import {
  CreationOptional,
  DataTypes,
  InferAttributes,
  InferCreationAttributes,
  Model,
  Sequelize,
} from "sequelize";
import sequelize from "../config/db";
import slugify from "slugify";

//Generated by GetModelInterface
export default interface CardKeyword
  extends Model<
    InferAttributes<CardKeyword>,
    InferCreationAttributes<CardKeyword>
  > {
  id: CreationOptional<number>;
  name: string;
  slug: CreationOptional<string>;
}

//Generated by GetModelDefinition
export const CardKeyword = sequelize.define<CardKeyword>(
  "CardKeyword",
  //Generated by GetModelFieldsDictionary
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
      field: "id",
    },
    name: {
      type: DataTypes.STRING,
      unique: true,
      field: "name",
    },
    slug: {
      type: DataTypes.STRING,
      unique: true,
    },
  },
  //Generated By GetModelOptionDict
  {
    name: { singular: "CardKeyword", plural: "CardKeywords" },
    tableName: "marvelduel_cardkeyword",
    timestamps: false,
  }
);

//Generated by GetModelHooks
CardKeyword.beforeCreate((CardKeyword: CardKeyword, options) => {
  CardKeyword.slug = slugify(CardKeyword.name, {
    lower: true,
    remove: /[*+~.()'"!:@]/g,
    replacement: "-",
  });
});

CardKeyword.beforeUpdate((CardKeyword: CardKeyword, options) => {
  CardKeyword.slug = slugify(CardKeyword.name, {
    lower: true,
    remove: /[*+~.()'"!:@]/g,
    replacement: "-",
  });
});

//Generated by GenerateSyncModel
export const CardKeywordSync = async () => {
  try {
    await CardKeyword.sync({ alter: true });
    console.log("Card Keyword table has been created!");
  } catch (error) {
    console.error(
      `Unable to create ${"Card Keyword".toLowerCase()} table:`,
      error
    );
  }
};
