//Generated by ImportCompleteModelFile
//Generated by GetCompleteModelFile

//Generated by GetModelImports
import {
  CreationOptional,
  DataTypes,
  InferAttributes,
  InferCreationAttributes,
  Model,
  Sequelize,
} from "sequelize";
import sequelize from "../config/db";

//Generated by GetModelInterface
export default interface Hero
  extends Model<InferAttributes<Hero>, InferCreationAttributes<Hero>> {
  belongsto_id: number;
}

//Generated by GetModelDefinition
export const Hero = sequelize.define<Hero>(
  "Hero",
  //Generated by GetModelFieldsDictionary
  {
    belongsto_id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      field: "belongsto_id",
      //Generated by GetReferencesKeyForModelCreationMigration
      references: {
        model: "marvelduel_belongsto",
        key: "id",
      },
      onUpdate: "CASCADE",
      onDelete: "CASCADE",
    },
  },
  //Generated By GetModelOptionDict
  {
    name: { singular: "Hero", plural: "Heroes" },
    tableName: "marvelduel_hero",
    timestamps: false,
  }
);

//Generated by GenerateSyncModel
export const HeroSync = async () => {
  try {
    await Hero.sync({ alter: true });
    console.log("Hero table has been created!");
  } catch (error) {
    console.error(`Unable to create ${"Hero".toLowerCase()} table:`, error);
  }
};
