//Generated by ImportCompleteModelFile
//Generated by GetCompleteModelFile

//Generated by GetModelImports
import {CreationOptional,DataTypes,InferAttributes,InferCreationAttributes,Model,Sequelize} from "sequelize";
import sequelize from "../config/db";
import slugify from "slugify";

//Generated by GetModelInterface
export default interface LockedDeck extends Model<InferAttributes<LockedDeck>, InferCreationAttributes<LockedDeck>>
{id: CreationOptional<number>;
name: string;
slug : CreationOptional<string>}

//Generated by GetModelDefinition
export const LockedDeck = sequelize.define<LockedDeck>(
"LockedDeck",
//Generated by GetModelFieldsDictionary
{
 id: {
  type: DataTypes.INTEGER,
  autoIncrement: true,
  primaryKey: true,
  field: "id"
 }
 ,
 name: {
  type: DataTypes.CHAR,
  unique: true,
  field: "name"
 }
 ,
 slug: {
  type: DataTypes.STRING,
  unique: true
 }
}
,
//Generated By GetModelOptionDict
{
  name: {singular: "LockedDeck",plural:"LockedDecks"},
  tableName: "lockeddecks",
  timestamps: false
}
);

//Generated by GetModelHooks
LockedDeck.beforeCreate((LockedDeck: LockedDeck, options) => {
  LockedDeck.slug = slugify(LockedDeck.name, {
    lower: true,
    remove: /[*+~.()'"!:@]/g,
    replacement: "-",
  });
});

LockedDeck.beforeUpdate((LockedDeck: LockedDeck, options) => {
  LockedDeck.slug = slugify(LockedDeck.name, {
    lower: true,
    remove: /[*+~.()'"!:@]/g,
    replacement: "-",
  });
});

//Generated by GenerateSyncModel
export const LockedDeckSync = async () => {
  try {
    await LockedDeck.sync({ alter: true });
    console.log("Locked Deck table has been created!");
  } catch (error) {
    console.error(
      `Unable to create ${"Locked Deck".toLowerCase()} table:`,
      error
    );
  }
};
