//Generated by WriteToMultiRoute_ts - multi route.ts
import sequelize from "@/config/db";
import { createCardSkill, updateCardSkill } from "@/utils/api/CardSkillLibs";
import { CardSkillUpdatePayload } from "@/interfaces/CardSkillInterfaces";
import { CardSkillSchema } from "@/schema/CardSkillSchema";
import {
  PRIMARY_KEY,
  UNIQUE_FIELDS,
} from "@/utils/constants/CardSkillConstants";
import handleSequelizeError from "@/utils/errorHandling";
import { checkDuplicateCombinations, returnJSONResponse } from "@/utils/utils";
import { NextResponse } from "next/server";

//Generated by GetMultiCreateModelPOSTRoute - GetMultiCreateModelPOSTRoute
export const POST = async (req: Request) => {
  const body = (await req.json()) as CardSkillUpdatePayload;
  const { CardSkills } = body;

  //Generated by GenerateUniquenessValidation
  //Validate record uniqueness

  UNIQUE_FIELDS.forEach((item) => {
    const uniquenessError = checkDuplicateCombinations(item, CardSkills);

    if (uniquenessError) {
      return returnJSONResponse({
        status: "error",
        error: uniquenessError,
        errorCode: 422,
      });
    }
  });

  const t = await sequelize.transaction();
  let recordsCreated = 0;

  for (const item of CardSkills) {
    try {
      await CardSkillSchema.validate(item);
    } catch (error) {
      return handleSequelizeError(error);
    }
  }

  try {
    for (const item of CardSkills) {
      if (item[PRIMARY_KEY] === "") {
        await createCardSkill(item, t);
        recordsCreated++;
      } else {
        await updateCardSkill(item, PRIMARY_KEY, t);
      }
    }

    await t.commit();

    return NextResponse.json({
      recordsCreated,
    });
  } catch (err) {
    await t.rollback();
    return handleSequelizeError(err);
  }
};
