//Generated by WriteToUsemodeldeletedialog_ts - useModelDeleteDialog.ts
import { CardKeywordDeletePayload } from "@/interfaces/CardKeywordInterfaces";
import { create } from "zustand";

type State = {
  recordsToDelete: string[];
  setRecordsToDelete: (recordsToDelete: string[]) => void;
  isDialogLoading: boolean;
  setIsDialogLoading: (isDialogLoading: boolean) => void;
  mutate?: (payload: CardKeywordDeletePayload) => void;
  setMutate: (mutate: (payload: CardKeywordDeletePayload) => void) => void;
};

// Create your store, which includes both state and (optionally) actions
const useCardKeywordDeleteDialog = create<State>((set) => ({
  recordsToDelete: [],
  setRecordsToDelete: (recordsToDelete) => set({ recordsToDelete }),
  isDialogLoading: false,
  setIsDialogLoading: (isDialogLoading) => set({ isDialogLoading }),
  setMutate: (mutate) => set({ mutate }),
}));

export { useCardKeywordDeleteDialog };
