//Generated by GetuseModelListts - useModelList.ts
"use client";
import { GetCardKeywordsResponse } from "@/interfaces/CardKeywordInterfaces";
import { CardKeywordSearchParams } from "@/interfaces/CardKeywordInterfaces";
import { BasicModel } from "@/interfaces/GeneralInterfaces";
import axiosClient from "@/utils/api";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";

const getCardKeywords = async (useName: boolean = false) => {
  const { data } = await axiosClient.get<GetCardKeywordsResponse>(
    `card-keywords`,
    {
      params: {
        fetchCount: "false",
        simpleOnly: "true",
      } as Partial<CardKeywordSearchParams>,
    }
  );

  return data.rows.map((item) => ({
    id: !useName ? item.id : item.name,
    name: item.name,
  }));
};

interface UseListProps {
  placeholderData?: BasicModel[];
  useName?: boolean;
}

const useCardKeywordList = (prop?: UseListProps) => {
  //local states
  const [mounted, setMounted] = useState(false);

  const _ = useQuery({
    queryKey: ["cardKeyword-list"],
    queryFn: () => getCardKeywords(prop?.useName),
    enabled: mounted,
    placeholderData: prop?.placeholderData,
  });

  useEffect(() => {
    setMounted(true);
  }, []);

  return _;
};

export default useCardKeywordList;
