//Generated by GetuseModelListts - useModelList.ts
"use client";
import { GetCardKeywordsResponse } from "@/interfaces/CardKeywordInterfaces";
import { CardKeywordSearchParams } from "@/interfaces/CardKeywordInterfaces";
import axiosClient from "@/utils/api";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";

const getCardKeywords = async () => {
  const { data } = await axiosClient.get<GetCardKeywordsResponse>(`card-keywords`, {
    params: {
      fetchCount: "false",
      simpleOnly: "true",
    } as Partial<CardKeywordSearchParams>,
  });

  return data.rows.map((item) => ({
    id: item.id,
    name: item.name,
  }));
};

const useCardKeywordList = () => {
  //local states
  const [mounted, setMounted] = useState(false);

  const _ = useQuery({
    queryKey: ["cardKeyword-list"],
    queryFn: getCardKeywords,
    enabled: mounted,
  });

  useEffect(() => {
    setMounted(true);
  }, []);

  return _;
};

export default useCardKeywordList;
