//Generated by WriteToDetailPageNext13 - Detail Page Sidebar
import CardForm from "@/components/cards/CardForm";
import { notFound } from "next/navigation";

export const metadata = {
  title: "Card Form",
};

async function getData(slug: string) {
  const res = await fetch(
    process.env.NEXT_PUBLIC_DOMAIN + "/api/cards/" + slug,
    { cache: "no-store" }
  );

  if (!res.ok) {
    throw notFound();
  }

  return res.json();
}

const CardFormPage = async ({ params }: { params: { slug: string } }) => {
  const data = params.slug === "new" ? null : await getData(params.slug);

  return (
    <div className="flex flex-col flex-1 w-full px-4 mx-auto text-sm lg:px-0 main-height-less-footer">
      <div className="flex flex-col w-full h-full gap-4 p-4 border rounded-sm border-border">
        <div className="flex flex-col h-full">
          <CardForm
            slug={params.slug}
            data={data}
          />
        </div>
      </div>
    </div>
  );
};

export default CardFormPage;
