//Generated by WriteToModelschema_ts - ModelSchema.ts
import * as Yup from "yup";

const CardUnitySchema = Yup.object().shape({
  //Generated by GetAllFieldValidationBySeqModel
  cardCompositions: Yup.string().required(
    "Card Compositions is a required field."
  ),
});

const CardUnityArraySchema = Yup.object().shape({
  CardUnities: Yup.array().of(
    Yup.object().shape({
      //Generated by GetAllArrayFieldValidationBySeqModel
      cardCompositions: Yup.string().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Card Compositions is a required field.")
          : schema.notRequired()
      ),
    })
  ),
});

export { CardUnitySchema, CardUnityArraySchema };
