//Generated by WriteToModelschema_ts - ModelSchema.ts
import * as Yup from "yup";

const CardUnityCardSchema = Yup.object().shape({
  //Generated by GetAllFieldValidationBySeqModel
  description: Yup.string().required("Description is a required field."),
  CardUnityId: Yup.number().required("Card Unity is a required field."),
  CardId: Yup.number().required("Card is a required field."),
});

const CardUnityCardArraySchema = Yup.object().shape({
  CardUnityCards: Yup.array().of(
    Yup.object().shape({
      //Generated by GetAllArrayFieldValidationBySeqModel
      description: Yup.string().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Description is a required field.")
          : schema.notRequired()
      ),
      CardUnityId: Yup.number().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Card Unity is a required field.")
          : schema.notRequired()
      ),
      CardId: Yup.number().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Card is a required field.")
          : schema.notRequired()
      ),
    })
  ),
});

export { CardUnityCardSchema, CardUnityCardArraySchema };
