//Generated by WriteToModelschema_ts
import * as Yup from "yup";

const CardSchema = Yup.object().shape({
  //Generated by GetAllFieldValidationBySeqModel
  name: Yup.string().required("Name is a required field."),
  type: Yup.string()
    .required("Type is a required field.")
    .oneOf(["Character", "Weapon", "Power", "Tactic"], "Type is invalid"),
  cost: Yup.number().required("Cost is a required field."),
  battleStyle: Yup.string()
    .nullable()
    .transform((value, originalValue) =>
      originalValue && originalValue.trim() !== "" ? value : null
    ),
  atk: Yup.number()
    .nullable()
    .transform((value, originalValue) =>
      originalValue && originalValue.trim() !== "" ? value : null
    ),
  shield: Yup.number()
    .nullable()
    .transform((value, originalValue) =>
      originalValue && originalValue.trim() !== "" ? value : null
    ),
  description: Yup.string()
    .nullable()
    .transform((value, originalValue) =>
      originalValue && originalValue.trim() !== "" ? value : null
    ),
  deckId: Yup.number().required("Deck is a required field."),
});

const CardArraySchema = Yup.object().shape({
  Cards: Yup.array().of(
    Yup.object().shape({
      //Generated by GetAllArrayFieldValidationBySeqModel
      name: Yup.string().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Name is a required field.")
          : schema.notRequired()
      ),
      type: Yup.string().when("touched", ([touched], schema) =>
        touched
          ? schema
              .required("Type is a required field.")
              .oneOf(
                ["Character", "Weapon", "Power", "Tactic"],
                "Type is invalid"
              )
          : schema.notRequired()
      ),
      cost: Yup.number().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Cost is a required field.")
          : schema.notRequired()
      ),
      battleStyle: Yup.string().nullable(),
      atk: Yup.number().nullable(),
      shield: Yup.number().nullable(),
      description: Yup.string().nullable(),
      deckId: Yup.number().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Deck is a required field.")
          : schema.notRequired()
      ),
    })
  ),
});

export { CardSchema, CardArraySchema };
