//Generated by WriteToModelschema_ts
import * as Yup from "yup";

const CardCardKeywordSchema = Yup.object().shape({
  //Generated by GetAllFieldValidationBySeqModel
  cardId: Yup.number().required("Card is a required field."),
  cardKeywordId: Yup.number().required("Card Keyword is a required field."),
});

const CardCardKeywordArraySchema = Yup.object().shape({
  CardCardKeywords: Yup.array().of(
    Yup.object().shape({
      //Generated by GetAllArrayFieldValidationBySeqModel
      cardId: Yup.number().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Card is a required field.")
          : schema.notRequired()
      ),
      cardKeywordId: Yup.number().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Card Keyword is a required field.")
          : schema.notRequired()
      ),
    })
  ),
});

export { CardCardKeywordSchema, CardCardKeywordArraySchema };
