//Generated by WriteToModelschema_ts - ModelSchema.ts
import * as Yup from "yup";

const CardSkillSchema = Yup.object().shape({
  //Generated by GetAllFieldValidationBySeqModel
  name: Yup.string().required("Name is a required field."),
  description: Yup.string().required("Description is a required field."),
});

const CardSkillArraySchema = Yup.object().shape({
  CardSkills: Yup.array().of(
    Yup.object().shape({
      //Generated by GetAllArrayFieldValidationBySeqModel
      name: Yup.string().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Name is a required field.")
          : schema.notRequired()
      ),
      description: Yup.string().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Description is a required field.")
          : schema.notRequired()
      ),
    })
  ),
});

export { CardSkillSchema, CardSkillArraySchema };
