//Generated by WriteToModelschema_ts - ModelSchema.ts
import * as Yup from "yup";

const DeckSchema = Yup.object().shape({
  //Generated by GetAllFieldValidationBySeqModel
  name: Yup.string().required("Name is a required field."),
  is_hero: Yup.boolean(),
  //Generated by GetAllRelatedLeftArrayValidation
  //Generated by GetRelatedLeftArrayValidation - GetRelatedLeftArrayValidation
  HeroSkills: Yup.array().of(
    Yup.object().shape({
      //Generated by GetAllArrayFieldValidationBySeqModel
      name: Yup.string().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Name is a required field.")
          : schema.notRequired()
      ),
      type: Yup.string().when("touched", ([touched], schema) =>
        touched
          ? schema
              .required("Type is a required field.")
              .oneOf(["Active", "Passive"], "Type is invalid")
          : schema.notRequired()
      ),
      cost: Yup.number().nullable(),
      description: Yup.string().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Description is a required field.")
          : schema.notRequired()
      ),
    })
  ),
});

const DeckArraySchema = Yup.object().shape({
  Decks: Yup.array().of(
    Yup.object().shape({
      //Generated by GetAllArrayFieldValidationBySeqModel
      name: Yup.string().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Name is a required field.")
          : schema.notRequired()
      ),
      is_hero: Yup.boolean().when("touched", ([touched], schema) =>
        touched ? schema : schema.notRequired()
      ),
    })
  ),
});

export { DeckSchema, DeckArraySchema };
