//Generated by WriteToModelschema_ts
import * as Yup from "yup";

const DeckSchema = Yup.object().shape({
  //Generated by GetAllFieldValidationBySeqModel
  name: Yup.string().required("Name is a required field."),
  is_hero: Yup.boolean(),
});

const DeckArraySchema = Yup.object().shape({
  Decks: Yup.array().of(
    Yup.object().shape({
      //Generated by GetAllArrayFieldValidationBySeqModel
      name: Yup.string().when("touched", ([touched], schema) =>
        touched
          ? schema.required("This is a required field.")
          : schema.notRequired()
      ),
      is_hero: Yup.boolean(),
    })
  ),
});

export { DeckSchema, DeckArraySchema };
